#cloud-config

# https://docs.cloud-init.io/en/latest/reference/examples.html

groups:
  - zac

users:
  - default
  - name: zac
    primary_group: zac
    groups: sudo
    # mkpasswd --method=SHA-512 --rounds=4096
    passwd: '$6$rounds=4096$Ypr8j8uagcZNyE5u$H8UztJlUoeGU1tETBR.OVFj5YfmL08yYrhuWAlPPJxXA.WHHet56I8rIzTah5LqhNylo8ZRPR/YSlliKVZcdV1'
    lock_passwd: false
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaDCYQ4VZiG+piPtB7fyLTJptSFyEMkM5VDCNEjnl4ladAKB6j3i9c8e7fmGirXZMdX92iB5/UmB8c6cHKjf7GShnLBDE477MSFOBlFic9HDDD67h92Z9WVgQG5d3TqH+sWc++UZiXy1wT5SjZuvrk+hdmBKtBdK2EwbxVO4gJ01eW46Pwbs2eIEgR1EGe69uBqW92voCyQ3s3H+wxviwSK/wmo3zBPhDZ7dE35m8TCNIc4DGYe/JcHv9ZIDkDyQjx1SGsfKhmL4oNjfFoDs7NBciOGIaYEj0NT/H7+TEjplM+lqMpG9TJ9d5eqYyM9c/cGqkJVK+nBYqLmV7eFkEiXQCUGHksXuBzumIeyyl5XFfR3Y9fNRL7oiIYstnfdEXEdocHI2RaeMAkijuFjLMlZnfa0/ocMSbO6NMvhIDo8ZNqY5lsEIZPCK02EEV9aOVEKnX2ulpGr1bOzlV2Xxwo/Okj2X+YB57+eg1/GdOrloJy0yG8bUsgUN0IabnPGlwU8dgW3hXT9aRrYTB8/z99+y7umV8zj4Swk1jnpdlKurAD6ZLoSbeV2IOlYA5yBNEbe0NxHg6K8Cl7JXhVO5JFPaYLWGEpbSE8OWIey4EZSLqHXVSYmltWD6T/wB1X+A2wdO6mlVct1uL/3pc2XAU+7s6O8MOfUA1XEpMQ0ZsNLQ== zac@zac (Fedora)

packages:
  - cmatrix
  - bash-completion

# https://docs.rke2.io/known_issues#networkmanager
runcmd:
  - sudo -u zac touch /home/zac/.hushlogin
  - |
    #!/bin/bash
    # https://www.reddit.com/r/rancher/comments/17va99x/rke2_install_failing_on_step_1_for_fresh_ubuntu/
    systemctl disable --now ufw
    systemctl disable --now apparmor.service
    systemctl daemon-reload
  - |
    #!/bin/bash
    CONFIG="/etc/NetworkManager/conf.d/rke2-canal.conf"
    mkdir -p "$(dirname "${CONFIG}")"
    echo "[keyfile]" > "${CONFIG}"
    echo "unmanaged-devices=interface-name:flannel*;interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali" >> "${CONFIG}"
    systemctl reload NetworkManager
    systemctl daemon-reload  # ???
  - |
    #!/bin/bash
    sudo modprobe erofs
    # Load required modules
    sudo modprobe overlay
    sudo modprobe br_netfilter
    # Ensure they persist on reboot
    # echo -e "overlay\nbr_netfilter" | sudo tee /etc/modules-load.d/rke2.conf
    echo -e "overlay\nbr_netfilter\nerofs" | sudo tee /etc/modules-load.d/rke2.conf
    # Fix potential MTU issues (common in KVM/libvirt)
    sudo ip link set dev eth0 mtu 1400

  - |
    #!/bin/bash
    echo "done" | sudo -u zac tee /home/zac/.init_done


