- name: Install rke2-server
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | sh -
  args:
    creates: /var/lib/rancher/rke2/server/node-token

- name: Start rke2-server service
  ansible.builtin.systemd_service:
    name: rke2-server.service
    state: started
    enabled: true

- name: Get the rke2-server node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: rke2_server_node_token_file

- name: Decode data and store as fact
  ansible.builtin.set_fact:
    rke2_server_node_token: "{{ rke2_server_node_token_file.content | ansible.builtin.b64decode }}"

- name: Copy kubeconfig to local PC
  ansible.builtin.fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ../rke2_kubeconfig.yaml
    flat: true
