---
- name: Provision control nodes
  hosts: control_nodes
  remote_user: root
  tasks:
    - name: Ensure desired packages are installed
      ansible.builtin.package:
        name:
          - cmatrix
        state: present

    - name: Run a command if a specific file does not exist
      ansible.builtin.shell: echo $((2+2)) > /root/hello.txt
      args:
        creates: "/root/hello.txt"

    - name: Fetch the file from the source host
      ansible.builtin.fetch:
        src: /root/hello.txt
        dest: /tmp/fetched_files/
        flat: yes  # Use 'flat: yes' to avoid creating a hostname/path structure in the destination

    - name: Install rke2-server
      ansible.builtin.shell: |
        curl -sfL https://get.rke2.io | sh -
      args:
        creates: /var/lib/rancher/rke2/server/node-token

    - name: Start rke2-server service
      ansible.builtin.systemd_service:
        name: rke2-server.service
        state: started
        enabled: true

    - name: Get the rke2-server node token
      ansible.builtin.slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: rke2_server_node_token_file

    - name: Decode data and store as fact
      ansible.builtin.set_fact:
        rke2_server_node_token: "{{ rke2_server_node_token_file.content | ansible.builtin.b64decode }}"

    # TODO: can I change 127.0.0.1 to the server IP automatically?
    # sed -i "s/127.0.0.1/$(terraform -chdir=terraform output -raw k8s_node_01_ip)/g" rke2_kubeconfig.yaml
    - name: Copy kubeconfig to local PC
      ansible.builtin.fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ../rke2_kubeconfig.yaml
        flat: true



- name: Provision worker nodes
  hosts: worker_nodes
  remote_user: root
  tasks:
    - name: Write "Hello World" into a new file
      ansible.builtin.copy:
        content: |
          Hello World!
          This file was created by an Ansible playbook.
        dest: /root/static_content_file.txt
        mode: '0644'

    - name: Copy the fetched file to the destination host
      ansible.builtin.copy:
        src: /tmp/fetched_files/hello.txt # Path on the Ansible controller
        dest: /root/hello_result.txt # Path on the destination host

    - name: Install rke2-agent
      ansible.builtin.shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Create /etc/rancher/rke2/
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory

    # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/template_module.html
    - name: Create /etc/rancher/rke2/config.yaml
      ansible.builtin.template:
        src: templates/rke2_agent_config.yaml
        dest: /etc/rancher/rke2/config.yaml

    - name: Start rke2-agent service
      ansible.builtin.systemd_service:
        name: rke2-agent.service
        state: started
        enabled: true


# https://dev.to/gsdiniz/automating-rke2-and-rancher-deployments-with-ansible-4gb3
# https://github.com/gsdiniz/ansible-rke-rancher/blob/main/playbook/roles/agent/tasks/main.yml

